id: aerohive-netconfig-ui

info:
  name: Aerohive NetConfig UI
  author: pussycat0x
  severity: info
  description: An Aerohive NetConfig user interface was detected. The NetConfig UI provides a fundamental set of configurations for configuring basic network and HiveManager connectivity settings, and uploading new IQ Engine images to Extreme Networks APs.
  reference:
    - https://docs.aerohive.com/330000/docs/help/english/ng/Content/reference/docs/online-help-systems.htm
  classification:
    cwe-id: CWE-200
    cpe: cpe:2.3:h:extremenetworks:aerohive_netconfig:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    shodan-query: http.title:"Aerohive NetConfig UI"
    product: aerohive_netconfig
    vendor: extremenetworks
  tags: panel,tech,hiveos,aerohive,discovery

http:
  - method: GET
    path:
      - "{{BaseURL}}/index.php5"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '<title>Aerohive NetConfig UI</title>'

      - type: status
        status:
          - 200

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - 'version" align="right" valign="bottom">([0-9.a-z]+)<\/td>'
# digest: 490a0046304402207cb64783aa74b01564c98830875ee985645dcf847d730ae2929b97351956037a02206c9705e3dba1b1cb70853a7d6544f04ff1a70b053382c600ac71be4232b19f9b:922c64590222798bb761d5b6d8e72950