id: amp-application-panel

info:
  name: Application Management Panel - Detect
  author: DhiyaneshDK
  severity: info
  description: Application Management Panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:cubecoders:amp:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: cubecoders
    product: amp
    shodan-query:
      - title:"AMP - Application Management Panel"
      - http.title:"amp - application management panel"
    fofa-query: title="amp - application management panel"
    google-query: intitle:"amp - application management panel"
  tags: panel,amp,cubecoders,discovery

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>AMP - Application Management Panel</title>"

      - type: word
        part: header
        words:
          - "text/html"
# digest: 4a0a00473045022100f99fd0a99c6a2f9455b22ca4ea1f96f8a9031ee10570dd9394a0e7ebc480a96d02201f945f7e869a49f4436301fff42693b396d04146793c880b909542fb3f30e9d7:922c64590222798bb761d5b6d8e72950