id: awstats-config

info:
  name: AWStats Config - Detect
  author: sheikhrishad
  severity: info
  description: AWStats configuration information was detected.
  reference: https://www.awstats.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 2
  tags: config,exposure,awstats,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/awstats/"
      - "{{BaseURL}}/awstats.conf"

    matchers:
      - type: word
        words:
          - "AWSTATS CONFIGURE"
          - "MAIN SETUP SECTION"
        condition: and

      - type: word
        words:
          - "Index of /awstats"
          - "Parent Directory"
        condition: and
# digest: 4a0a004730450220339f3b0b45209e1e5388798ca40db629a765db77c123360e3b4903d8758a6074022100823009596a9980eb34bb3177e51368eee06f04c7084a0cc22c43a36d79d0d5b0:922c64590222798bb761d5b6d8e72950