id: azure-pipelines-exposed

info:
  name: Azure Pipelines Configuration File Disclosure
  author: DhiyaneshDk
  severity: medium
  description: Azure Pipelines internal critical file is disclosed.
  classification:
    cpe: cpe:2.3:a:microsoft:azure_pipelines_agent:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    vendor: microsoft
    product: azure_pipelines_agent
    shodan-query: html:"azure-pipelines.yml"
  tags: config,exposure,azure,microsoft,cloud,devops,files,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.azure-pipelines.yml"
      - "{{BaseURL}}/azure-pipelines.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "trigger:"
          - "pool:"
          - "variables:"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a004730450221008ad969bae5d23e9bdc9a8bdd87968e6d5fd0486343e31883a33cfccb315b146a02204a44cbfc88e189e415626833dfdfbee2d8ca914c75d2b40e0359d886560b76c2:922c64590222798bb761d5b6d8e72950