id: babel-config-exposure

info:
  name: Babel Configuration - Detect
  author: DhiyaneshDK
  severity: info
  description: Babel configuration information was detected.
  reference:
    - https://babeljs.io/docs/en/configuration
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
    cpe: cpe:2.3:a:pocoo:babel:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"babel.config.js"
    product: babel
    vendor: pocoo
  tags: exposure,config,file,vuln

http:
  - method: GET
    path:
      - '{{BaseURL}}/babel.config.js'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'module.exports = {'
          - 'presets: ['
        condition: and

      - type: status
        status:
          - 200
# digest: 490a00463044022009952bcb36ae290932ece85fbbab5b27d1be7bb6932ecf0b8ab1acff9596bec1022011fbdf5ac1c3a1efbfaba7cfa3795cb02bd49b24fc38cfaa8bf55e5298daf49e:922c64590222798bb761d5b6d8e72950