id: composer-auth-json

info:
  name: Composer-auth Json File Disclosure
  author: DhiyaneshDK
  severity: low
  description: Composer Auth Josn file is disclosed.
  reference:
    - https://www.exploit-db.com/ghdb/5768
  classification:
    cpe: cpe:2.3:a:getcomposer:composer:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    vendor: getcomposer
    product: composer
    google-query: intext:"index of /" ".composer-auth.json"
  tags: exposure,devops,files,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.composer-auth.json"
      - "{{BaseURL}}/vendor/webmozart/assert/.composer-auth.json"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'github-oauth'
          - 'github.com'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a0047304502207fb6b82c8a77c463fc9695d410d28037a896e71b9133a181316160a00555397c022100e6f968dcd05e18938eb1953cb227bc3b6db97b76412cd39ff8f474109778810f:922c64590222798bb761d5b6d8e72950