id: config-json

info:
  name: Configuration File - Detect
  author: geeknik
  severity: medium
  description: Multiple configuration files were detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 4
    github-query: filename:config.json
  tags: config,exposure,files,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/config/default.json"
      - "{{BaseURL}}/config.json"
      - "{{BaseURL}}/config/config.json"
      - "{{BaseURL}}/credentials/config.json"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"api_keys":'
          - '"aws":'
          - '"server":'
          - '"users":'
          - '"password":'
          - '"user"'
          - '"path":'
        condition: or

      - type: word
        part: header
        words:
          - "text/html"
        negative: true

      - type: status
        status:
          - 200
# digest: 490a0046304402200e1625effa7a19cb6534e3c367a68a0ebcde2e7a02092cbcddbeed680a8c2d9c0220222b973cba13f9c44cd53edb327c0d5b244a7a4860b558d3beb7971232fc1fa2:922c64590222798bb761d5b6d8e72950