id: crowdin

info:
  name: Crowdin User Name Information - Detect
  author: dwisiswant0
  severity: info
  description: Crowdin user name information check was conducted.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: osint,osint-hobby,crowdin,discovery

self-contained: true

http:
  - method: GET
    path:
      - "https://crowdin.com/profile/{{user}}"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        part: body
        words:
          - ") – Crowdin"
# digest: 4b0a00483046022100eea6155ea03fddb6ae5bb953275ab5c141823cf97f678dcb0adfef439168e792022100a7fa33d741fe4f17f51931dd4b08122c22e2ded070767de68c147aaccc3d2782:922c64590222798bb761d5b6d8e72950