id: default-oracle-application-page

info:
  name: Oracle Application Server Containers
  author: dhiyaneshDk,righettod
  severity: info
  metadata:
    max-request: 1
    shodan-query: http.title:"Oracle Application Server Containers"
  tags: tech,oracle,discovery

http:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers:
      - type: word
        words:
          - "<TITLE>Oracle Application Server"
        part: body

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '(?i)\s+\(([0-9.]+)\)'
# digest: 4a0a0047304502201fa404b332f51eb70c887dddda7b6b99dc81b1d450b6325afe3b1b043b294274022100f0651fe10115cf49ab157d3e3c729b12e107c7f0bd933d8b20f52db9fe363d21:922c64590222798bb761d5b6d8e72950