id: detect-drone-config

info:
  name: Drone - Configuration Detection
  author: geeknik
  severity: high
  description: Drone configuration was discovered.
  reference:
    - https://github.com/drone/drone
  metadata:
    max-request: 1
  tags: config,exposure,drone,discovery

http:
  - method: GET
    path:
      - "{{BaseURL}}/.drone.yml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "kind:"
          - "name:"
          - "steps:"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a0047304502203c43358588f41e6f0368b5a515ddbd2bf1f58a32e102f5a820f46b03307e0c0e022100cbbad32152dbc24e37c4b25afdc33787161e3917981f8e1488a4a1d01f459a27:922c64590222798bb761d5b6d8e72950