id: ecology-mysql-config

info:
  name: Fanwei OA E-Office - Information Disclosure
  author: ritikchaddha
  severity: medium
  description: |
    Fanwei E-Office mysql_config.ini file can be directly accessed, leaking database account password and other information.
  metadata:
    verified: true
    max-request: 1
    fofa-query: app="泛微-EOffice"
  tags: fanwei,ecology,exposure,config,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/mysql_config.ini"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "dataurl"
          - "datapassword"
          - "datauser"
        condition: and

      - type: word
        part: header
        words:
          - text/plain

      - type: status
        status:
          - 200
# digest: 4a0a004730450221008cb9e3a34e4de83a28def4c3977e2a3dd34f3bcfc515f51fbd18a654bd55331a02203ecb041bc7dd1e525a909d10935e0b8bb790eb4f7f03ebbd2e894e553aa9be18:922c64590222798bb761d5b6d8e72950