id: elastic-kibana-config

info:
  name: Elastic Kibana Config - File Disclosure
  author: DhiyaneshDk
  severity: medium
  description: |
    Elastic Kibana Config file is exposed.
  reference:
    - https://www.elastic.co/guide/en/kibana/current/settings.html
  metadata:
    verified: true
    max-request: 1
    fofa-query: body="kibana.yml"
  tags: exposure,elastic,kibana,files,config,vuln

http:
  - method: GET
    path:
      - '{{BaseURL}}/kibana.yml'

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(content_type, "application/octet-stream")'
          - 'contains_all(body, "elasticsearch.username:","elasticsearch.password:")'
        condition: and
# digest: 4a0a00473045022048d59b2b3a52dfe211fb88ea71353dd7200d838fc8a07098b42e7574bda76992022100dd17545759dfa0a8770e2fc66eaf835ad2b0390f4edd6d580280eee805044137:922c64590222798bb761d5b6d8e72950