id: esphome-panel

info:
  name: ESPHome Login Panel - Detect
  author: fabaff
  severity: info
  description: ESPHome login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:esphome:esphome:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: esphome
    product: esphome
    shodan-query:
      - title:"Login - ESPHome"
      - http.title:"login - esphome"
    fofa-query: title="login - esphome"
    google-query: intitle:"login - esphome"
  tags: panel,esphome,iot,discovery

http:
  - method: GET
    path:
      - '{{BaseURL}}/login'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'class="esphome-header'

      - type: status
        status:
          - 200
# digest: 490a0046304402206737541254f364f06e1b45cbfe25edd48736720462f31feb8f8f4a645c3f1786022000e8a2140469cec4f5fb51dd0deba6cd777e0bc11c06c820f173d2f99afe47ef:922c64590222798bb761d5b6d8e72950