id: gcloud-config-default

info:
  name: Google Cloud Default Config - Detect
  author: DhiyaneshDK
  severity: info
  description: Google Cloud default configuration was detected.
  reference: https://cloud.google.com
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
    cpe: cpe:2.3:a:google:cloud_platform:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:"access_tokens.db"
    product: cloud_platform
    vendor: google
  tags: google,cloud,devops,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/configurations/config_default"
      - "{{BaseURL}}/.config/gcloud/configurations/config_default"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '[core]'
          - 'account'
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100f45f11145d51f8a4731deb540fd2f06997633783b2a52e435f2d2568e505a7b5022100ebedf0a1706916592de4911722fa89de0fb5d86815b552b9e160b60bb5c5cbaf:922c64590222798bb761d5b6d8e72950