id: github-page-config

info:
  name: Github pages config file
  author: hahwul
  severity: info
  description: Find github pages config file.
  metadata:
    max-request: 1
  tags: github,exposure,config,files,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/_config.yml"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "jekyll"
          - "title"
          - "baseurl"
        condition: and
# digest: 4a0a00473045022100820d6d1626dd51cdcf759f8a650c5762587a59fdae59f63647c9b66a5e90774e0220512ad0b6c38a8ed52353742bc8b774fcf193a6726b816135ef2d6f00f68a51c3:922c64590222798bb761d5b6d8e72950