id: golangci-config

info:
  name: GolangCI-Lint Configuration File - Detect
  author: Hardik-Solanki
  severity: info
  description: GolangCI-Lint configuration file was detected.
  reference:
    - https://github.com/maurosoria/dirsearch/blob/master/db/dicc.txt
    - https://golangci-lint.run/usage/configuration/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 4
    github-query: filename:golangci.yml
  tags: exposure,golang,devops,cicd,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.golangci.yml"
      - "{{BaseURL}}/.golangci.yaml"
      - "{{BaseURL}}/.golangci.toml"
      - "{{BaseURL}}/.golangci.json"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'linters:'
          - 'linters-settings:'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022024434a91b387f572bf53c6d5a95642a8e77ba36d47cd89af1a52a347c7ec1f5d022100c5a0e1dca7db24fb1b656a03903e941afee8c5d84e362098265b45bc06dc8b9d:922c64590222798bb761d5b6d8e72950