id: grandstream-device-configuration

info:
  name: Grandstream Device Configuration
  author: dhiyaneshDK
  severity: info
  description: Exposed Grandstream device configuration page detected.
  classification:
    cpe: cpe:2.3:o:grandstream:ht801_firmware:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: grandstream
    product: ht801_firmware
    shodan-query: http.title:"Grandstream Device Configuration"
  tags: iot,discovery

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Grandstream Device Configuration</title>'

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100b946e83ff5dc62773c68dbc211b9a7f69bdb49728d916263d4780b746da2a24c02200f750ae7734be78a6f3433ef7118d8f62206073f2be12d890c22dad473851fbb:922c64590222798bb761d5b6d8e72950