id: htaccess-config

info:
  name: HTaccess config file
  author: Yash Anand @yashanand155
  severity: info
  metadata:
    max-request: 6
  tags: miscellaneous,misc,config,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/.htaccess"
      - "{{BaseURL}}/example.htaccess"
      - "{{BaseURL}}/_.htaccess"
      - "{{BaseURL}}/sample.htaccess"
      - "{{BaseURL}}/a.htaccess"
      - "{{BaseURL}}/htaccess_for_page_not_found_redirects.htaccess"

    stop-at-first-match: true
    matchers:
      - type: word
        words:
          - RewriteRule
          - </IfModule>
          - <IfModule
        condition: and
# digest: 4a0a00473045022100dc33aaac9082f5b78f65688c3c53cc14f02afa71d2cf63946a4bb13a6573b6b6022040e802bba311b8a6682634283d4d53a637c8ecd9a4fedb6eab3a9310c9a90baf:922c64590222798bb761d5b6d8e72950