id: joomla-config-dist-file

info:
  name: Joomla! Configuration File - Detect
  author: oppsec
  severity: low
  description: Joomla! configuration.php-dist file was detected.
  metadata:
    max-request: 1
  tags: config,exposure,joomla,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/configuration.php-dist"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "Joomla"
          - "JConfig"
          - "@package"
        condition: and

      - type: word
        words:
          - "text/plain"
        part: header

      - type: status
        status:
          - 200
# digest: 4a0a00473045022005e0497f7a05c9b64579e7b2b4eed0efbe463c6c1fb54131802879382a661a34022100dd3f783d24611dc9ea9a56c167673aaa426c0ee2f251ec9a4e722cdb3b135053:922c64590222798bb761d5b6d8e72950