id: jsconfig-json

info:
  name: Visual Studio Code jsconfig.json - Detect
  author: DhiyaneshDk
  severity: info
  description: Visual Studio Code jsconfig.json was detected.
  reference:
    - https://code.visualstudio.com/docs/languages/jsconfig
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"jsconfig.json"
  tags: devops,exposure,jsconfig,config,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/jsconfig.json"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '"compilerOptions": {'
          - '"typeAcquisition": {'
        condition: or

      - type: word
        part: header
        words:
          - 'application/json'

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100aecfcbc6dc476d63a58ebcf1f5a0abd7bf963ef55693a497a474aad99b92eafc02205c0c8e98b4c769938d120d9a928700752926f7c719da8cd6c70e5826a3f0fe9c:922c64590222798bb761d5b6d8e72950