id: lighttpd-config-file

info:
  name: Lighttpd Config File - File Disclosure
  author: DhiyaneshDk
  severity: low
  description: |
    Lighttpd Config file is exposed.
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"lighttpd.conf"
  tags: exposure,files,lighttpd,vuln

http:
  - method: GET
    path:
      - '{{BaseURL}}/lighttpd.conf'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'server.document-root ='
          - 'server.port ='
        condition: and
        case-insensitive: true

      - type: word
        part: content_type
        words:
          - 'application/octet-stream'
# digest: 4b0a00483046022100808a7bdca50454b11308ab849b10387e98f55716ea2b9762fedc750d0cb8dab0022100ba224d9946ab7ff12bf90237af562c5a8631bb0cc9d68172b81a077a4b17282a:922c64590222798bb761d5b6d8e72950