id: manageengine-applications-manager

info:
  name: ZOHO ManageEngine Applications Manager Panel - Detected
  author: dhiyaneshDK
  severity: info
  description: ZOHO ManageEngine panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:a:zohocorp:manageengine_applications_manager:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    vendor: zohocorp
    product: manageengine_applications_manager
  tags: panel,zoho,manageengine,zohocorp,discovery

http:
  - method: GET
    path:
      - '{{BaseURL}}/index.do'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Applications Manager Login Screen</title>'

      - type: status
        status:
          - 200
# digest: 490a0046304402202e5244d32533bc23927f7ef60254f27da77d61d08fcd190d802a2497a0fde9d802207846ff8ce7aa5128b76d3e5a957551b4487774ea4b6b017cd3ca9fb7f40aee0f:922c64590222798bb761d5b6d8e72950