id: misconfigured-concrete5

info:
  name: Misconfigured Concrete5
  author: pdteam
  severity: low
  description: Concrete5 CMS is misconfigured.
  metadata:
    max-request: 1
  tags: misconfig,concrete,cms,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    host-redirects: true
    max-redirects: 2
    matchers:
      - type: word
        part: body
        words:
          - 'concrete5 has encountered an issue'
# digest: 4a0a004730450220154ff8045b6dcc6da77a892b0be7d8b397f5d7e875a3485876c2059137947c44022100f10b273e67778009f3f733aaa1b356d3969c4a2021c7dc5367dfc98c35612621:922c64590222798bb761d5b6d8e72950