id: neo4j-neodash-config

info:
  name: Neo4j Neodash Config - Exposure
  author: icarot
  severity: medium
  description: |
    Detects the file config.json from Neo4j Neodash web application, it contains information about DB connection with Neo4J.
  classification:
    cpe: cpe:2.3:a:neo4j:*:*:*:*:*:*:*:*:*
  metadata:
    max-request: 1
    verified: true
    vendor: neo4j
    product: neodash
    shodan-query: title:"NeoDash"
  tags: config,exposure,neodash,neo4j,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/config.json"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'standaloneHost'
          - 'standalonePort'
          - 'standaloneDatabase'
        condition: and

      - type: word
        part: header
        words:
          - 'application/json'

      - type: status
        status:
          - 200

    extractors:
      - type: json
        name: config
        part: body
        json:
          - '.standaloneDatabase,.standaloneUsername,.standalonePassword'
# digest: 4a0a0047304502200dcb8881074012a06548cb484f6c6e0a2261349191d1117eefe83c5876c4178c0221009ba92f37e5e341b80bf7e3a9a4033993b1948983eee85c44ed57f04dbf8f94d2:922c64590222798bb761d5b6d8e72950