id: netbeans-config

info:
  name: Netbeans Config - Detect
  author: sbani
  severity: info
  description: Netbeans configuration information was detected.
  reference:
    - https://netbeans.apache.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: netbeans,config,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/nbproject/project.properties"

    matchers-condition: and
    matchers:
      - type: regex
        regex:
          - "(?mi)^src.dir="
          - "(?mi)^build.[a-zA-Z]+="
          - "(?mi)^jar.[a-zA-Z]+="
        condition: or

      - type: status
        status:
          - 200
# digest: 490a00463044022079e9e9d50d12e6f35d34fe5e92465de3f8d1c0bedc9e67144bef356df39f35c9022068ee2ec7119bccda807885bf3d13d1d93e431ade6096afce51f008508b470dcc:922c64590222798bb761d5b6d8e72950