id: parameters-config

info:
  name: Parameters.yml - File Discovery
  author: DhiyaneshDK
  severity: high
  description: Parameters.yml was discovered.
  reference: https://www.exploit-db.com/ghdb/5986
  metadata:
    verified: true
    max-request: 4
    shodan-query: html:"parameters.yml"
  tags: exposure,cloud,devops,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/parameters.yml"
      - "{{BaseURL}}/app/config/parameters.yml"
      - "{{BaseURL}}/parameters.yml.dist"
      - "{{BaseURL}}/app/config/parameters.yml.dist"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'parameters:'
          - 'database_user'
          - 'database_password'
        condition: and

      - type: status
        status:
          - 200
# digest: 490a00463044022005f4fd757d3de997726ac0abc907d09bf26b6005d2f146b3ef9c6af2cd4636f40220680978dc6db839f1cc9a9dd1123e37ddbb45fd39934aa7d739073d2b4644ded7:922c64590222798bb761d5b6d8e72950