id: phinx-config

info:
  name: Phinx Configuration Exposure
  author: DhiyaneshDk
  severity: medium
  description: Phinx configuration file was exposed.
  reference:
    - https://book.cakephp.org/phinx/0/en/configuration.html
    - https://github.com/cakephp/phinx
    - https://www.tenable.com/plugins/was/113433
    - https://phinx.org/
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"phinx.yml"
  tags: devops,exposure,files,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/phinx.yml"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'paths:'
          - 'environments:'
          - 'development:'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022025a1e3a0c5dc9b1404bb696f8a8c362a785fa70fdc8bc8f965cd5be871a00787022100dcaab109c11880652700764794dc3e4d936bef78ccae24c09b6ac9c775bc79de:922c64590222798bb761d5b6d8e72950