id: phpstan-config

info:
  name: PHPStan Configuration Page - Detect
  author: DhiyaneshDK
  severity: info
  description: PHPStan configuration page was detected.
  reference: https://phpstan.org/
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"phpstan.neon"
  tags: devops,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/phpstan.neon"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'parameters:'

      - type: word
        part: header
        words:
          - "text/html"
          - "application/javascript"
        negative: true

      - type: status
        status:
          - 200
# digest: 4a0a0047304502207b42fa6a1c617276c09eeb7599e583298f4fdca84059f4968ea8c73e2eb91ebf0221009f8fd276e3f2443905413b89f10399de6ddb20ae1b73d4418fcd062427a69781:922c64590222798bb761d5b6d8e72950