id: pipeline-configuration

info:
  name: Pipeline Configuration Exposure
  author: DhiyaneshDK
  severity: info
  classification:
    cpe: cpe:2.3:a:jenkins:pipeline\\:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: jenkins
    product: pipeline\\
    shodan-query: html:"pipeline.yaml"
  tags: devops,exposure,cicd,files,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/pipeline.yaml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'system:'
          - 'project_name:'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100bd5e3239f496e5bfcbbba803e8f870b67a53cae594fbcfabcc099d29f638f32402201b7cf704a7437ddcb7eb78684f1ad6adf2755ac3d351763a7573529d4fef7e02:922c64590222798bb761d5b6d8e72950