id: pipfile-config

info:
  name: Pipfile Config - Detect
  author: DhiyaneshDK
  severity: info
  description: Pipfile configuration information was detected.
  reference:
    - https://pypi.org/project
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"Pipfile"
  tags: exposure,pip,devops,cicd,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/Pipfile"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - '[[source]]'
          - '[packages]'
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100a55c70e3548fbc75dcb6c8fffbecb5f206c5d907471012740f5483dcafa50eae022100b925c180ab323452c1a0d561ce4fcf2caddc383301344313d3a845862c32b251:922c64590222798bb761d5b6d8e72950