id: prometheus-log

info:
  name: Exposed Prometheus
  author: dhiyaneshDK,thevillagehacker
  severity: low
  description: Prometheus instance is exposed.
  metadata:
    max-request: 3
  tags: prometheus,misconfig,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/prometheus"
      - "{{BaseURL}}/actuator/prometheus"
      - "{{BaseURL}}/actuator/prometheus;%2f..%2f..%2f"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'gateway_request_total'
          - 'logback_events_total'
        condition: or

      - type: status
        status:
          - 200
# digest: 490a004630440220538d6f4cd86e46ed8707cde073651b3a9de72ea41d1386efe4e1ef4e464c636c02202c02e1a54728f0fbbf3ce1fcc914afd09947f2baf0d09f19a1e5d9530b8a27b6:922c64590222798bb761d5b6d8e72950