id: prometheus-unauth

info:
  name: Prometheus Monitoring System - Unauthenticated
  author: pussycat0x
  severity: high
  description: |
    Detects unauthenticated access to Prometheus Time Series Collection and Processing Server by checking for specific elements in the response from the `/graph` endpoint.
  metadata:
    verified: true
    max-request: 2
    shodan-query: http.title:"Prometheus Time Series"
  tags: unauth,prometheus,misconfig,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/config"
      - "{{BaseURL}}/api/v1/status/config"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "global:"
          - "scrape_configs:"
          - "scrape_interval"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022034e04fe6dafe2bdfb3605a6ad2841a70e519d290bb3a35bfeffa4ac940b4e930022100a427e0d7f91a157ec6849d5e94ecdf36f4aeb6f212bf72c66b91573eee1bd924:922c64590222798bb761d5b6d8e72950