id: prometheus-exporter

info:
  name: Prometheus exporter detect
  author: jarijaas
  severity: info
  description: Prometheus exporter detector
  reference:
    - https://github.com/prometheus/prometheus/wiki/Default-port-allocations
  metadata:
    max-request: 1
  tags: prometheus,misconfig,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'Exporter'
          - '<a href="/metrics">Metrics</a>'
        condition: and

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - "<title>(.*?)</title>"
# digest: 4a0a00473045022100b048a875e42d752c5e70813fc139283024114aebc5c4f8050e70a0bb6a0cb62702202a63ad88d5862c9945a49a7924a546610b44cafcb6b3ca6b94469d7c005b4859:922c64590222798bb761d5b6d8e72950