id: rails-database-config

info:
  name: Ruby on Rails Database Configuration File - Detect
  author: pdteam,geeknik
  severity: high
  description: Ruby on Rails database configuration file was detected, which may contain database credentials.
  reference: https://guides.rubyonrails.org/configuring.html#configuring-a-database
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,rails,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/config/database.yml"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "adapter:"
          - "database:"
          - "production:"
        condition: and
        part: body

      - type: status
        status:
          - 200
# digest: 4b0a0048304602210087422e9b36ccb2c18e1739b16a4b7b9dd0f4c89d301d9cd25d0501994477eb19022100ffe4f61cac1a9f7d16237fff94251a20c700ca0a690491771759d2bb5e6a42c0:922c64590222798bb761d5b6d8e72950