id: redmine-settings

info:
  name: Redmine settings.yml File Disclosure
  author: DhiyaneshDK
  severity: info
  reference: https://www.exploit-db.com/ghdb/5796
  classification:
    cpe: cpe:2.3:a:redmine:redmine:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 3
    vendor: redmine
    product: redmine
    google-query: intitle:"index of" "settings.yml"
  tags: misconfig,redmine,devops,files,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/settings.yml"
      - "{{BaseURL}}/config/settings.yml"
      - "{{BaseURL}}/redmine/config/settings.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'format:'
          - 'default:'
          - 'Redmine'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100cc5a1b1c9f78f5002d95e5fae6d25b24b7b9fc7de167a3b6a9b05aea8b56227d02202f3c85fffa57c8dc9bf3c634a6be13f3671cb17e632e53c46513af4e2320e797:922c64590222798bb761d5b6d8e72950