id: redmine-config

info:
  name: Redmine Configuration File - Detect
  author: DhiyaneshDK
  severity: high
  description: Redmine configuration file was detected.
  reference:
    - https://www.exploit-db.com/ghdb/5803
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
    cpe: cpe:2.3:a:redmine:redmine:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 3
    google-query: intitle:"index of" configuration.yml
    product: redmine
    vendor: redmine
  tags: exposure,redmine,devops,edb,files,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/configuration.yml"
      - "{{BaseURL}}/config/configuration.yml"
      - "{{BaseURL}}/redmine/config/configuration.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "user_name"
          - "password"
          - "Redmine"
        condition: and

      - type: word
        part: header
        words:
          - "application/json"
          - "text/html"
        negative: true
        condition: and

      - type: status
        status:
          - 200
# digest: 490a00463044022005cb7b6913cf6f342f5c52d599f38b5d53a5108e82ea0dd26b8ef63b504647ad0220301e83640272137e0301bbf855a85a878a3da0fd2de4f605d3ddcdbd63e412be:922c64590222798bb761d5b6d8e72950