id: rollup-js-config

info:
  name: Rollup.js Configuration - Detect
  author: DhiyaneshDK
  severity: info
  description: Rollup configuration was detected.
  reference:
    - https://rollup.docschina.org/guide/en/#configuration-files
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:"rollup.config.js"
  tags: exposure,devops,cicd,rollupjs,vuln

http:
  - method: GET
    path:
      - '{{BaseURL}}/rollup.config.js'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'export default ['
          - 'input:'
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100933a69c6c58310cf3098c691bfdec3a273766f6e33c3d8151e57228d459083f8022100d2073a1478d8d22c173dd03c4c8340009d0ac1fb92055bf5a3a4a4bc41105254:922c64590222798bb761d5b6d8e72950