id: samba-config

info:
  name: Samba Config - Detect
  author: sheikhrishad
  severity: info
  description: Samba configuration information was detected.
  reference:
    - https://www.samba.org/samba/docs/using_samba/ch06.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: config,exposure,smb,samba,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/smb.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "configuration file"
          - "samba"
        condition: and

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100b8930bd8e3aaa595cfdb4e89c5cb4a7a7737614e3384961a2194bbc5060fca9f02210093282ca2af2d3bde9b248b28351c6c8e4526f3d4272acfbfe2308ea283b0b658:922c64590222798bb761d5b6d8e72950