id: settings-php-files

info:
  name: settings.php - Information Disclosure
  author: sheikhrishad
  severity: medium
  description: settings.php source code was detected via backup files.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  metadata:
    max-request: 7
  tags: exposure,backup,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/settings.php.bak"
      - "{{BaseURL}}/settings.php.dist"
      - "{{BaseURL}}/settings.php.old"
      - "{{BaseURL}}/settings.php.save"
      - "{{BaseURL}}/settings.php.swp"
      - "{{BaseURL}}/settings.php.txt"
      - "{{BaseURL}}/config/settings.old.php"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "DB_NAME"
          - "DB"
        condition: and

      - type: status
        status:
          - 200
# digest: 490a0046304402201d6bc365d8e186803116f9f3baceb9cc06da8a3db4a63be40700fa4e45db179a0220467614f32a5490e9562ab9f45d668b5ef880552ff60783c10600048b46da2d31:922c64590222798bb761d5b6d8e72950