id: sftp-deployment-config

info:
  name: Atom SFTP Configuration File - Detect
  author: geeknik
  severity: high
  description: |
    Atom SFTP deployment configuration file was detected. File contains server details and credentials.
  reference:
    - https://atom.io/packages/sftp-deployment
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  metadata:
    verified: true
    max-request: 1
    github-query: filename:deployment-config.json sftp
  tags: sftp,atom,config,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/deployment-config.json"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"host":'
          - '"username":'
          - '"password":'
          - '"remotePath":'
        condition: and

      - type: status
        status:
          - 200
# digest: 490a00463044022035051e86c5fb186a1b9179e14917ac7f4b8990956094aa1f7562d8e52275349e02203adbac0f232aa96e851064e63d0ef00f96dec82e29d802bee96b4fd24fb8549a:922c64590222798bb761d5b6d8e72950