id: slack-config-access-token

info:
  name: Slack Config Access Token
  author: DhiyaneshDK
  severity: info
  reference:
    - https://github.com/semgrep/semgrep-rules/blob/develop/generic/secrets/gitleaks/slack-config-access-token.txt
    - https://github.com/semgrep/semgrep-rules/blob/develop/generic/secrets/gitleaks/slack-config-access-token.yaml
    - https://api.slack.com/authentication
  metadata:
    max-request: 1
  tags: exposure,token,slack,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    extractors:
      - type: regex
        part: body
        regex:
          - (?i)(xoxe.xox[bp]-\d-[A-Z0-9]{163,166})
# digest: 4b0a00483046022100dacc9cd9a34e13ea15006f8dfb71bcd438cec31c5c4731677294b046c759f157022100f45a40b18470231a37e72782180164ee7a4009ccd5f7f2b8d740ef75c813bd72:922c64590222798bb761d5b6d8e72950