id: sonic-wall-application

info:
  name: SonicWall Appliance Management Console Login Panel - Detect
  author: DhiyaneshDk,Tess
  severity: info
  description: SonicWall Appliance Management Console login panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
    cpe: cpe:2.3:o:sonicwall:sma1000_firmware:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: sonicwall
    product: sma1000_firmware
    shodan-query:
      - title:"Appliance Management Console Login"
      - http.title:"appliance management console login"
    fofa-query: title="appliance management console login"
    google-query: intitle:"appliance management console login"
  tags: panel,sonicwall,login,discovery

http:
  - method: GET
    path:
      - "{{BaseURL}}/login.do"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '<title>Appliance Management Console Login</title>'

      - type: status
        status:
          - 200
# digest: 490a0046304402202aeb7ebce618070dc17f0801f4d0397dad5907a0fa60a592b50747ba558ccd5002201557aa9505903e5d793b0b9dd39a9f40530c7608559095397ec0ffc56dbb8346:922c64590222798bb761d5b6d8e72950