id: springboot-configprops

info:
  name: Detect Springboot Configprops Actuator
  author: that_juan_,dwisiswant0,wdahlenb
  severity: low
  description: Sensitive environment variables may not be masked
  metadata:
    max-request: 2
  tags: springboot,exposure,misconfig,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/configprops"
      - "{{BaseURL}}/actuator/configprops"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "org.springframework.boot.actuate"
          - "beans"
          - "context"
        condition: and

      - type: status
        status:
          - 200

      - type: word
        words:
          - "application/json"
          - "application/vnd.spring-boot.actuator"
          - "application/vnd.spring-boot.actuator.v1+json"
        condition: or
        part: header
# digest: 490a00463044022058b014d78339f9d33e82ca6554f49780455ac5ae31f9aa6189dfd521494a674102206df0005f2c4c4d738e54d53de75b4ce41ddf6964686a7940c9336195bf1e97c1:922c64590222798bb761d5b6d8e72950