id: svnserve-config

info:
  name: Svnserve Configuration File - Detect
  author: sheikhrishad
  severity: info
  description: Svnserve configuration file was detected.
  reference: https://linux.die.net/man/8/svnserve
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
    cpe: cpe:2.3:a:apache:subversion:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    google-query: intext:"configuration of the svnserve daemon"
    product: subversion
    vendor: apache
  tags: config,exposure,svnserve,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/svnserve.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "This file controls the configuration of the svnserve daemon"

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100b00d2106c50a8fc5c4385daf33d4502ef7c2d332dfee366ebe2d82ce50c9e181022100c3a9739f706779692ebd966b145229a2bcc7238196f54c13912f54cdc02c54c4:922c64590222798bb761d5b6d8e72950