id: symfony-security

info:
  name: Symfony security.yml File Disclosure
  author: DhiyaneshDK
  severity: info
  classification:
    cpe: cpe:2.3:a:sensiolabs:symfony:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 3
    vendor: sensiolabs
    product: symfony
    google-query: intitle:"index of" "security.yml"
  tags: symfony,devops,exposure,files,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/security.yml"
      - "{{BaseURL}}/config/security.yml"
      - "{{BaseURL}}/app/config/security.yml"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - 'security:'
          - 'providers:'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a004730450220642af7032b347cfb99711c8f05ba638c82af1e5c7b3cd068b986e80b4fe592c20221009a09bdcc7b168c866ef47da97d841978edf2109c29e6cb688184157b8efa6319:922c64590222798bb761d5b6d8e72950