id: typo3-composer

info:
  name: Typo3 composer.json Exposure
  author: 0x_Akoko
  severity: low
  description: |
    The web application is based on Typo3 CMS. A sensitive file has been found. Access to such files must be restricted, as it may lead to disclosure of sensitive information about the web application.
  reference:
    - https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.0/Breaking-83302-ComposerRestrictsInstallationOfTypo3cms.html
  classification:
    cpe: cpe:2.3:a:typo3:typo3:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 1
    vendor: typo3
    product: typo3
    shodan-query: "X-TYPO3-Parsetime: 0ms"
  tags: typo3,cms,exposure,misconfig,vuln

http:
  - method: GET
    path:
      - '{{BaseURL}}/typo3/sysext/install/composer.json'

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "The Install Tool mounted as the module Tools>Install in TYPO3."
          - "typo3-cms-framework"
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100bbf1b71ede7eb39d44fc2424530a8c82e6490c91212f6b3331c9aa708a90abc9022018c27f604836dae2f3b78c1f0eb7f2f47c0c316c73e127833a9b9f3c23ff2833:922c64590222798bb761d5b6d8e72950