id: wgetrc-config

info:
  name: Wgetrc Configuration File - Detect
  author: DhiyaneshDK
  severity: info
  description: Wgetrc configuration file was detected.
  reference:
    - https://www.gnu.org/software/wget/manual/html_node/Wgetrc-Commands.html
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0
    cwe-id: CWE-200
    cpe: cpe:2.3:a:gnu:wget:*:*:*:*:*:*:*:*
  metadata:
    verified: true
    max-request: 2
    shodan-query: html:".wgetrc"
    product: wget
    vendor: gnu
  tags: devops,exposure,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/wgetrc"
      - "{{BaseURL}}/.wgetrc"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '/etc/wgetrc'
          - 'wget.info'

      - type: word
        part: header
        words:
          - 'application/octet-stream'

      - type: status
        status:
          - 200
# digest: 4b0a00483046022100c6edddbe66c28624dfbfd14aef62bc26e08b694b9abcf201eca338d1e8545aa102210083f060329ee68d817ec59ff5f405b957458c36248a980e9245a93c87801b4e11:922c64590222798bb761d5b6d8e72950