id: xampp-environment-variables

info:
  name: XAMPP Environment Variables Exposure
  author: melbadry9,DhiyaneshDK
  severity: low
  description: printenv.pl file is exposed in XAMPP leaking environment variables.
  metadata:
    max-request: 1
  tags: exposure,xampp,files,vuln

http:
  - method: GET
    path:
      - "{{BaseURL}}/cgi-bin/printenv.pl"

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "<TITLE>Environment Variables</TITLE>"
          - "Environment Variables:"
        condition: and

      - type: word
        part: header
        words:
          - "text/html"

      - type: status
        status:
          - 200
# digest: 4a0a00473045022100dcdea261b43744ac455045e2d98525876e2d1e8073aa2aa749413a50a11899130220277e78b547e9b3e7e04ec7acd22c8520db520d45ecbc3e4c7d4f9319e26be7f3:922c64590222798bb761d5b6d8e72950